name: Model Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn matplotlib seaborn

    - name: Run model training and testing
      run: |
        python train.py

    - name: Upload score
      run: |
        echo "Model Score: $(cat score.txt)" > $GITHUB_STEP_SUMMARY

    - name: Upload feature importance plot
      uses: actions/upload-artifact@v2
      with:
        name: feature_importance
        path: feature_importance.png

    - name: Upload residuals plot
      uses: actions/upload-artifact@v2
      with:
        name: residuals
        path: residuals.png

    - name: Commit and push residuals.png
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add residuals.png
        git commit -m "Add residuals.png"
        git push origin HEAD

    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "Add residuals.png" --body "This PR adds the residuals.png file." --base main